language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: beta-xcode6.1

addons:
  apt:
    packages:
      - libv8-dev

env:
  matrix:
  - osx_image

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install v8-315; fi

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then Rscript -e 'covr::codecov()'; fi
