language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      env: R_CODECOV=true
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2
      brew_packages: v8-315
    - os: osx
      osx_image: beta-xcode6.1
      env: R_NOBREW=true

addons:
  apt:
    packages:
      - libv8-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - if [[ "${R_NOBREW}" ]]; then curl -OLSs https://raw.githubusercontent.com/Homebrew/install/master/uninstall; sudo ruby uninstall --force; fi

after_success:
  - if [ "${R_CODECOV}" ]; then Rscript -e 'covr::codecov()'; fi
