language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
      ENV: R_CODECOV=true
    - os: osx
      osx_image: xcode7.2
      env: R_BREW=true
    - os: osx
      osx_image: beta-xcode6.1
      sudo: required
      env: R_NOBREW=true

addons:
  apt:
    packages:
      - libv8-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before install:
  - if [[ "${R_BREW}" ]]; then brew update; brew install v8-315; fi
  - if [[ "${R_NOBREW}" ]]; then sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"; fi

after_success:
  - if [ "${R_CODECOV}" ]; then Rscript -e 'covr::codecov()'; fi
