language: r
cache: packages

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: beta-xcode6.1
      env: NOBREW=true

addons:
  apt:
    packages:
      - libv8-dev

env:
  matrix:
  - osx_image

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && -z "$NOBREW" ]]; then brew update; brew install v8-315; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && -n "$NOBREW" ]]; then ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"; fi

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then Rscript -e 'covr::codecov()'; fi
