language: r
cache: packages
latex: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode9.4
      before_install:
        - brew install v8@3.15
        - brew link --force v8@3.15
    - os: osx
      osx_image: xcode8.3
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages:
      - libv8-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
